name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install required packages
        run: sudo apt-get -y --no-install-recommends install libvips42 libvips-dev
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
      - name: Code Quality
        run: bundle exec rake code_quality
